# Generated by Django 5.2.8 on 2025-12-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='username',
        ),
    ]
