# Generated by Django 5.2.8 on 2025-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.PositiveBigIntegerField()),
                ('isbn', models.CharField(max_length=55)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
